#Create Seller 
POST http://localhost:3000/users
content-type: application/json

{
    "email": "seller3@seller3.com",
    "username": "seller3",
    "name": "seller3",
    "lastname": "seller3",
    "password": "Seller123",
    "role": "seller",
    "city": "durango",   
    "state": "durango"   
}

###
# Create Customer
POST http://localhost:3000/users
content-type: application/json


{
    "email": "customer3@customer3.com",
    "username": "customer3",
    "name": "customer",
    "lastname": "customer",
    "password": "Customer123",
    "role": "customer",
    "city": "durango",   
    "state": "durango"   
}
 
###

# Get a single user based on the jwt token
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYTJiOTMwOS01OGQxLTExZWUtYTNlMS0wMjQyYzBhODUwMDMiLCJ1c2VybmFtZSI6ImN1c3RvbWVyMSIsInRpbWVzdGFtcCI6IjIwMjMtMDktMjFUMjI6NTQ6NDMuMjU3WiIsImlhdCI6MTY5NTMzNjg4M30.Jduq0RZJcsRAgJypO5x2sVG1JkQ7QoS-kpePxMS3Zco

###

# Update user (password is required)
PATCH http://localhost:3000/users
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYTJiOTMwOS01OGQxLTExZWUtYTNlMS0wMjQyYzBhODUwMDMiLCJ1c2VybmFtZSI6ImN1c3RvbWVyMSIsInRpbWVzdGFtcCI6IjIwMjMtMDktMjFUMjI6NTQ6NDMuMjU3WiIsImlhdCI6MTY5NTMzNjg4M30.Jduq0RZJcsRAgJypO5x2sVG1JkQ7QoS-kpePxMS3Zco

{
    "email": "customer@customer.com",
    "username": "customer1",
    "name": "customer",
    "lastname": "customer",
    "password": "Customer123",
    "city": "durango",   
    "state": "durango"   
}
