version: '3'
services:
  # voxaroo_backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   container_name: voxaroo_backend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - .:/app
  #   links:
  #     - mysql

  mysql:
    image: mysql:latest
    container_name: my-mysql
    environment:
      - MYSQL_ROOT_PASSWORD:admin123
      - MYSQL_DATABASE:voxaroo
      - MYSQL_USER:fabian
      - MYSQL_PASSWORD:admin
    ports:
      - "3306:3306"
    volumes: 
      - ./db/data:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin
    ports: 
      - "8080:80" 
    environment:
      - MYSQL_ROOT_PASSWORD:admin123
      - PMA_HOST=mysql
    
