version: '3.9'
services: 
  # voxaroo_backend:
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   links:
      # - mysql 

  mysql:
    image: mysql
    ports: 
      - "3306:3306"
    environment: 
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=voxaroo
    volumes:
      - ./db/data:/var/lib/mysql